version: "3.9"

services:

  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    volumes:
      - ./Backend:/app
    depends_on:
      - milvus
      - ml_service

  ml_service:
    build: ./ml_service
    container_name: ml_service
    ports:
      - "8000:8000"
    env_file:
      - ml_service/.env
    volumes:
      - ./ml_service:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - milvus

volumes:
  milvus_data:
