version: "3.8"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./volumes/etcd:/etcd
    command: >
      etcd
      --data-dir=/etcd
      --advertise-client-urls=http://0.0.0.0:2379
      --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"

  milvus:
    image: milvusdb/milvus:v2.4.3
    container_name: milvus-standalone
    shm_size: 1g
    depends_on:
      - etcd
    environment:
      ETCD_ENDPOINTS: etcd:2379
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    command: ["milvus", "run", "standalone"]

  minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    container_name: milvus-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data --console-address ":9001"
    volumes:
      - ./volumes/minio:/minio_data
    ports:
      - "9000:9000"
      - "9001:9001"
