"""
Standardized reject reasons for face preprocessing
"""

# Quality rejection reasons
BLUR_TOO_HIGH = "BLUR_TOO_HIGH"
POSE_OUT_OF_RANGE = "POSE_OUT_OF_RANGE"
FACE_TOO_SMALL = "FACE_TOO_SMALL"
LOW_LIGHT = "LOW_LIGHT"
OVER_EXPOSED = "OVER_EXPOSED"
ALIGNMENT_FAILED = "ALIGNMENT_FAILED"
INVALID_LANDMARKS = "INVALID_LANDMARKS"
PREPROCESSING_FAILED = "PREPROCESSING_FAILED"

# Backward-compatible aliases
LOW_BRIGHTNESS = LOW_LIGHT
HIGH_BRIGHTNESS = OVER_EXPOSED

# All valid reject reasons
ALL_REJECT_REASONS = {
    BLUR_TOO_HIGH,
    POSE_OUT_OF_RANGE,
    FACE_TOO_SMALL,
    LOW_LIGHT,
    OVER_EXPOSED,
    ALIGNMENT_FAILED,
    INVALID_LANDMARKS,
    PREPROCESSING_FAILED,
    LOW_BRIGHTNESS,
    HIGH_BRIGHTNESS,
}
