"""
Standardized reject reasons for face preprocessing
"""

# Quality rejection reasons
BLUR_TOO_HIGH = "BLUR_TOO_HIGH"
POSE_OUT_OF_RANGE = "POSE_OUT_OF_RANGE"
FACE_TOO_SMALL = "FACE_TOO_SMALL"
LOW_BRIGHTNESS = "LOW_BRIGHTNESS"
HIGH_BRIGHTNESS = "HIGH_BRIGHTNESS"
ALIGNMENT_FAILED = "ALIGNMENT_FAILED"
INVALID_LANDMARKS = "INVALID_LANDMARKS"

# All valid reject reasons
ALL_REJECT_REASONS = {
    BLUR_TOO_HIGH,
    POSE_OUT_OF_RANGE,
    FACE_TOO_SMALL,
    LOW_BRIGHTNESS,
    HIGH_BRIGHTNESS,
    ALIGNMENT_FAILED,
    INVALID_LANDMARKS,
}
